version: "3"

services:
  nginx:
    restart: always
    build:
      context: ./nginx/
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
  postgres:
    image: postgres:latest
  redis:
    image: redis:latest
  backend-api:
    build:
      context: ./backend-server/
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./backend-server:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres_password
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
  worker:
    build:
      context: ./worker/
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
